# ref: https://github.com/marketplace/actions/git-sync-action
on:
  schedule: 
    # sync every hour on the half hour
    - cron: '30 * * * *'
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync-master-branch
        uses: aks-lts/git-sync@main
        with:
          source_repo: "kubernetes/kubernetes"
          destination_repo: "git@github.com:aks-lts/kubernetes.git"
          source_branch: "master"
          destination_branch: "master"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: git-sync-release-1.27
        uses: aks-lts/git-sync@main
        with:
            source_repo: "kubernetes/kubernetes"
            destination_repo: "git@github.com:aks-lts/kubernetes.git"
            source_branch: "release-1.27"
            destination_branch: "release-1.27"
            destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: git-sync-release-1.28
        uses: aks-lts/git-sync@main
        with:
            source_repo: "kubernetes/kubernetes"
            destination_repo: "git@github.com:aks-lts/kubernetes.git"
            source_branch: "release-1.28"
            destination_branch: "release-1.28"
            destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: git-sync-release-1.29
        uses: aks-lts/git-sync@main
        with:
            source_repo: "kubernetes/kubernetes"
            destination_repo: "git@github.com:aks-lts/kubernetes.git"
            source_branch: "release-1.29"
            destination_branch: "release-1.29"
            destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: git-sync-release-1.30
        uses: aks-lts/git-sync@main
        with:
          source_repo: "kubernetes/kubernetes"
          destination_repo: "git@github.com:aks-lts/kubernetes.git"
          source_branch: "release-1.30"
          destination_branch: "release-1.30"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: git-sync-release-1.31
        uses: aks-lts/git-sync@main
        with:
            source_repo: "kubernetes/kubernetes"
            destination_repo: "git@github.com:aks-lts/kubernetes.git"
            source_branch: "release-1.31"
            destination_branch: "release-1.31"
            destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
      - name: git-sync-tags #SHOULD WE RESTRICT TAGS? 
        uses: aks-lts/git-sync@main
        with:
          source_repo: "kubernetes/kubernetes"
          destination_repo: "git@github.com:aks-lts/kubernetes.git"
          source_branch: "refs/tags/*"
          destination_branch: "refs/tags/*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY` 
     